### ISSUE TITLE
Issues追加

### ISSUE THREAD

**Issue by hekoshabo** [dandk105/webapp_study#4]
### 気になること

- Githubのお作法ってあるのかな？人さまのリポジトリにおじゃました時、ここは触っちゃダメとか。

### 知りたいこと

- グロナビメニュー（Isuues / Actions / Projects / Wiki …）がどんな機能でどんな場面で使うのか知りたい

### 不明点

- ~~Isuue書いてみてねの場所がここであってるかわからずどきどき。~~
- ~~dandk105さんのリポジトリじゃなく自分とこでやりな、だったらどうしよう。~~
- 違ってた！コメントじゃなくて、NewIssuesだった。

**Comment by dandk105** [comment]
@hekoshabo 
記載ありがとうございますー！

やり方間違ってないです！

まずは、お作法とグローバルメニューですね！
グローバルメニューは前社内でもお話ししたので、同じような記載をwikiの方に追加しておきます！

お作法は、権限の理由で気にする必要がない可能性もあるので、そこ含めて説明します！

**Comment by hekoshabo** [comment]
@dandk105 
グローバルメニューについて、wikiよみました！
ブランチ数と作業ブランチをどこで見ればいいかがわかりました！
「タグ付けされたバージョン」っていうのが、どういう役割のものなのか、ちょっとピンとこなかったです。

たとえば機能Aと機能Bを追加する場合、機能Aを作成する人は「機能A」というブランチを切って作業するよーなイメージなんですが
「タグ付けされたバージョン」ってどんな場合に使う感じでしょうか？

**Comment by hekoshabo** [comment]
（Issues間違ってクローズしちゃったです。ググったらプロジェクトの再開は見つけられたけどIssuesの再開は見つけられず…）

**Comment by dandk105** [comment]
@hekoshabo 
返信遅くなってすみません　😭 
分からない所の質問ありがとうございます！　感謝🙏 
タグ付けされたバージョンについてですが、簡単に例を示すと、プロダクトをデプロイされる時に利用されます！
プルリクのレビューが終了して、本番環境にいつでもデプロイできる状態になったら、
そのバージョンにVersion:1.2　のようにタグ付けしてあげるイメージです。

これをしてあげることによりどこまでの機能や変更が本番環境に反映されているかがわかるということです。
[gitのタグについての解説](https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E5%9F%BA%E6%9C%AC-%E3%82%BF%E3%82%B0)

**Comment by hekoshabo** [comment]
@dandk105 
タグ付けについてご説明ありがとうございます！なんとなくわかった気がします…！

例えば私とdandk105さんがチームで、私が機能Aでdandk105さんが機能Bを実装する場合、お互いブランチを切って実装しレビューOKしたら、私の機能Aのブランチとdandk105さんの機能Bのブランチに、Version:1.2（仮）がタグ付けされるって感じであってますでしょうか？

**Comment by dandk105** [comment]
@hekoshabo 
hekoshaboさんが開発した機能がレビューOKしリリースされる場合は、Version:1.2（仮）が付与されるのはあっています！
しかしその後の理解が少し異なります！タグづけされるのは、hekoshaboさんのブランチのみになり、
私のブランチはタグづけされたコミットを取り込み新しいバージョンでタグづけして、リリースされます。
以下に例の図になります！

```mermaid
---
title: 質問返答のGitのイメージ図
---
gitGraph
      commit id: "first"
branch hekoshabo
 branch dandk105
   checkout dandk105
       commit
       commit
   checkout hekoshabo
       commit
       commit tag: "Version:1.2（仮)"
checkout main
merge hekoshabo
checkout dandk105
commit tag:"Version:1.3 (仮)"
checkout main
merge dandk105
```

**Comment by hekoshabo** [comment]
質問の内容が変わったため、[別Issues起票](https://github.com/dandk105/webapp_study/issues/28)。こちらはクローズします！
